language: node_js
node_js:
- '7'
dist: trusty
before_deploy:
- npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: AXHVGYkAd/f0dhqHDLtSEzpUyA+EFGUzU2+bPbhw4BQthiJMW+KGos8wMK0Q/5EURhqrN3BpugUEhnQw4w0pEfc6H9BFaqGYcbcAHSnYtcZXnYo51iJBZ97a/t4cQlrmKRar7kwJRMnsiBrzoeoW2oA2tfHNwcSkUBWGmbiDTyYDLr3MvQRpXYvaWl0POFeiAkuYkSNtvziuDXVLNIJ1QKPBEMC6hV/e//E9XNur3lhxROouIAsQ1zZCXUamESeDr7Ddx3tStehfnS7Deefta1gFUI+BtCe7t7XuBuz1mz/3ZtNX7B78fQ3pOjPmiF0+HdW41/HNmcIiFiGMKfm/uyKEu7X66MGtLB9bPR7xRB8K6AHPI+1yxOjDK1wYMzzgMc2psaPUPWyvZtP4brijkJ1ZI9nfWsBGOwDB8VkdyUBsCLlBUnuNT4Ka8aDH9TETQnYvEYeMYA182uRog56vPQZpqQJBkkCbHUctjS2UBHbLyqhueEjx3d3yghBlQn/vC2f17tD+W74dtKlgVrfJaLDx38+cLYO0a7jbSvlUh1HrARycfN9KbNeDGJb1it/DPwo6t6tnKPnKHKywSePkF8rLHB6CkUWL6Nz7wRGQWqwSwzd0tdZ+vxi7A5/7UewZhJIQCWiOXvSQGIIZ+Mt7OV9I5DaoBwLZcjEKaDoUlD0=
  project: bistro-112-staging
  message: LIVE!
  on:
    branch: staging
- provider: firebase
  skip_cleanup: true
  token:
    secure: AXHVGYkAd/f0dhqHDLtSEzpUyA+EFGUzU2+bPbhw4BQthiJMW+KGos8wMK0Q/5EURhqrN3BpugUEhnQw4w0pEfc6H9BFaqGYcbcAHSnYtcZXnYo51iJBZ97a/t4cQlrmKRar7kwJRMnsiBrzoeoW2oA2tfHNwcSkUBWGmbiDTyYDLr3MvQRpXYvaWl0POFeiAkuYkSNtvziuDXVLNIJ1QKPBEMC6hV/e//E9XNur3lhxROouIAsQ1zZCXUamESeDr7Ddx3tStehfnS7Deefta1gFUI+BtCe7t7XuBuz1mz/3ZtNX7B78fQ3pOjPmiF0+HdW41/HNmcIiFiGMKfm/uyKEu7X66MGtLB9bPR7xRB8K6AHPI+1yxOjDK1wYMzzgMc2psaPUPWyvZtP4brijkJ1ZI9nfWsBGOwDB8VkdyUBsCLlBUnuNT4Ka8aDH9TETQnYvEYeMYA182uRog56vPQZpqQJBkkCbHUctjS2UBHbLyqhueEjx3d3yghBlQn/vC2f17tD+W74dtKlgVrfJaLDx38+cLYO0a7jbSvlUh1HrARycfN9KbNeDGJb1it/DPwo6t6tnKPnKHKywSePkF8rLHB6CkUWL6Nz7wRGQWqwSwzd0tdZ+vxi7A5/7UewZhJIQCWiOXvSQGIIZ+Mt7OV9I5DaoBwLZcjEKaDoUlD0=
  project: bistro-112-production
  message: LIVE!
  on:
    branch: master
notifications:
  slack:
    secure: JhLz/TNH7v5BgTwIMoC200jaJx+CrxRfjUc0MMYriK+wq6Ydrnx3wQUQNNIq3zu35aiAarAZyiZvkG4c1/oYwbIVvw3QiJ1zrzjwMmgmarVVF67G//qun746x/bPzSH4Cb6B8zXVA6cH/0hxaq8NnQDRYHmrLuF4dKn9/zuwH97BqRkcpyOFmcKRu22GPSpQgmAKzicU6KFaLVMusABrs6mYecqlmSqrGlSZaK5O9TGlhga9c/efhGzHy7s3RsqZJmfZA2Wv6m0HQlMZvhfTynRXQIPQFDLpFW2BOlikT6HP62mESFPNNwc1ai9NIf9dlb8Je0V+whQ7geWsuOjGknCxeajq84I8q/vClEcG/vONcyOU9oUe4qx5el7zMd3ZSqpKTSkfhhrQ2HBwQ/RnTNnXCunkkJz54FAI2h2vJdEI2RCRM6df4EPURnWw0Zavhd6dyoRjeldkhs5mi1zAR+O8gsA/LBI5vmmE8thGDOeCZ3VybGVAu4qhUjoh0isN+6PcbrMy+B8a7RLnq+P978hTjXSf70jjZWFExcuvM8B/AtI9GDRRYngikNiEgcN6CbXxk7fWW4T8Oiq0LY+htF467dIsKejdWrONvhMAw8wWJUqXDFODC64kUQhXrLtvt1FCmu+JM6WzaHHqU0+1Cfqo0aIzdAvHEzQCGXTCu7k=
